#cloud-config
package_update: true
packages:
  - docker.io
runcmd:
  - curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - cd /root/
  - git clone https://github.com/marcware/GHA-DevOps-Backend.git
  - cd /GHA-DevOps-Backend/
  - cp .env.pro .env 
  - docker pull marcware/books_app:lastest
  - docker-compose -f docker-compose-prod.yml up -d
  - docker exec -it lumen-book composer install
  - chmod -R ug+rwx storage vendor

    
