---
- name: Deploy example app to my-server.com
  hosts: all
  vars:
    ansistrano_deploy_to: "/var/www/html/"
    ansistrano_git_repo_tree: "Web"
    ansistrano_keep_releases: 3
    ansistrano_deploy_via: "git"
    ansistrano_git_repo: https://github.com/MarcosGeekHubs/Hello_Terraform_IaC
    ansistrano_git_branch: main
    ansistrano_after_cleanup_tasks_file: "{{ playbook_dir }}/after_cleanup.yaml"
  roles:
     - { role: ansistrano.deploy }