---
- hosts: all
  become: yes
  vars:
    ansistrano_deploy_to: "/var/www/html/"
    ansistrano_git_repo_tree: "Web"
    ansistrano_keep_releases: 3
    ansistrano_deploy_via: "git"
    ansistrano_git_repo: https://github.com/ansistrano/symfony-deploy-example.git
    ansistrano_git_branch: master
    ansistrano_git_ssh_opts: "-o StrictHostKeyChecking=no"
    ansistrano_git_depth: 1
    ansistrano_git_identity_key_path: "./../id_rsa"
    ansistrano_allow_anonymous_stats: no
  roles:
    - { role: ansistrano.deploy }